apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_DATABASE: appdb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppass123
  MYSQL_ROOT_PASSWORD: rootpass123
  DB_NAME: appdb
  DB_USER: appuser
  DB_PASSWORD: apppass123
